version: "3.8"
services:
  es:     
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8080
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - efk
  flb:
    image: fluent/fluent-bit:1.5
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/etc/fluentbit.conf"]
    volumes:
      - ./collector/fluentbit2.conf:/etc/fluentbit.conf
      - logs:/tmp/
    networks:
      - efk
  dashboard:
    image: kibana:7.9.1
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    networks:
      - efk
  app:
    image: vicxu/pingpong:latest
    ports: 
      - 13333:13333
    environment:
      - LOGFILE=/tmp/log
    networks:
      - efk
    volumes:
      - logs:/tmp/
    
volumes:
  esdata:
    driver: local
  logs:
    driver: local

networks:
  efk:
    driver: bridge