version: '3'

services:
  zk:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka
  broker:
    image: wurstmeister/kafka
    depends_on:
      - zk
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    ports:
      - 9092:9092
    networks:
      - kafka


networks:
  kafka:
    driver: bridge