#!/bin/bash

# https://github.com/moovweb/gvm
# machine must have minal 2G memory. https://github.com/moovweb/gvm/issues/155

sudo apt-get install -y curl git mercurial make binutils bison gcc build-essential

bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

source ${HOME}/.gvm/scripts/gvm
gvm version
gvm install go1.4 -B
gvm use go1.4
export GOROOT_BOOTSTRAP=$GOROOT
echo "export GOROOT_BOOTSTRAP=$GOROOT" >> ${HOME}/.bashrc

version=$1

if [ -n "$version"]; then
  gvm install $1
fi
