#!/bin/bash

DB_TYPE=$1
DB_NAME=$2
USER=$3
PWD=$4


if [ -z "$USER" ]; then
USER="dev"
fi

if [ -z "$PWD" ]; then
PWD="dev"
fi

if [ -z "$DB_NAME" ]; then
DB_NAME="dev"
fi

function run_pg()
{
  PG_CONFIG="${HOME}/etc/pg/pg.conf"

  [ $(docker ps -f "name=pg" | wc -l | xargs) ==  "2" ]
  if [ $? ]; then
    echo "container pg is running"
    docker kill pg
    docker container prune -f
    echo "kill and prune pg"
  fi

  echo "dbname: $DB_NAME, user: $USER, pwd: $PWD, container_name: pg"

  if [ -f "$PG_CONFIG" ]; then
    docker run -d --name pg -e POSTGRES_USER=${USER} \
            -e PGDATA=/var/lib/postgresql/data/pgdata \
            -e POSTGRES_PASSWORD=${PWD} \
            -e POSTGRES_DB=${DB_NAME}
            -p 5432:5432 \
            -v ${PG_CONFIG}:/usr/share/postgresql/postgresql.conf \
            -v ${HOME}/var/lib/pgdata:/var/lib/postgresql/data/pgdata \
            postgres:12.3-alpine -c 'config_file=/usr/share/postgresql/postgresql.conf'
  else
    docker run -d --name pg -e POSTGRES_USER=dev \
              -e PGDATA=/var/lib/postgresql/data/pgdata \
              -e POSTGRES_PASSWORD=dev \
              -p 5432:5432 \
              -v ${HOME}/var/lib/pgdata:/var/lib/postgresql/data/pgdata \
              postgres:12.3-alpine
  fi
}


function run_mysql()
{
  [ $(docker ps -f "name=mysql" | wc -l | xargs) ==  "2" ]
  if [ $? ]; then
    echo "container mysql is running"
    docker kill mysql
    docker container prune -f
    echo "kill and prune mysql"
  fi

  echo "dbname: $DB_NAME, user: $USER, pwd: $PWD, container_name: mysql"

  docker run --name mysql -e MYSQL_USER=${USER} -e MYSQL_PASSWORD=${PWD} \
         -e MYSQL_ROOT_PASSWORD=${PWD} \
         -v ${HOME}/var/lib/mysqldata:/var/lib/mysql \
         -p 3306:3306 -e MYSQL_DATABASE=${DB_NAME} -d \
         mysql:8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
}


case "$DB_TYPE" in
  pg|postgre|postgresql) run_pg
    ;;
  mysql) run_mysql
    ;;
esac


function run_redis() {
  docker run --name redis -d -p 6379:6379 redis
}